---
- name: remove AH user with infra.ah_configuration
  hosts: localhost
  vars:
    ah_host: hub.justinmelhorn.com
    ah_username: admin
    ah_password: "{{ _password_ }}"
  roles:
    - infra.ah_configuration.user
      vars:
        ah_users:
          - username: "{{ _user_ }}"
            state: absent